# Generated by Django 5.0.7 on 2024-07-26 11:16

import django.db.models.deletion
import main.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('service', models.CharField(choices=[('', 'Select'), ('US', 'User'), ('SE', 'Seller'), ('RE', 'Renter'), ('SAR', 'Seller And Renter')], max_length=100)),
                ('service_provider', models.CharField(choices=[('', 'Select'), ('CY', 'Company'), ('PE', 'Private Entrepreneur')], default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('', 'Select'), ('AR', 'Armenia'), ('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AU', 'Australia'), ('CN', 'China'), ('JP', 'Japan'), ('IN', 'India'), ('BR', 'Brazil'), ('ZA', 'South Africa'), ('RU', 'Russia'), ('MX', 'Mexico'), ('KR', 'South Korea'), ('SG', 'Singapore'), ('NZ', 'New Zealand'), ('SE', 'Sweden'), ('NO', 'Norway'), ('FI', 'Finland')], max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'BASE USER',
                'verbose_name_plural': 'BASE USERS',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='companies/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('office_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('fax_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('additional_documents', models.FileField(blank=True, upload_to='')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COMPANY',
                'verbose_name_plural': 'COMPANIES',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.agent_photo_upload_to)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, choices=[('', 'Select a position'), ('broker_owner', 'Broker/Owner'), ('managing_broker', 'Managing Broker'), ('real_estate_agent', 'Real Estate Agent'), ('listing_agent', 'Listing Agent'), ('buyers_agent', "Buyer's Agent"), ('property_manager', 'Property Manager'), ('leasing_agent', 'Leasing Agent'), ('commercial_agent', 'Commercial Real Estate Agent')], max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('office_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.TextField(blank=True)),
                ('additional_documents', models.FileField(blank=True, upload_to='')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_agents', to='main.companyprofile')),
            ],
            options={
                'verbose_name': 'AGENT',
                'verbose_name_plural': 'AGENTS',
            },
        ),
        migrations.CreateModel(
            name='PrivateEntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.agent_photo_upload_to)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.TextField(blank=True)),
                ('additional_documents', models.FileField(blank=True, upload_to='')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PRIVATE ENTERPRENEUR',
                'verbose_name_plural': 'PRIVATE ENTERPRENEURS',
            },
        ),
        migrations.CreateModel(
            name='SimpleUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_account/%Y/%m/%d/')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SIMPLE USER',
                'verbose_name_plural': 'SIMPLE USERS',
            },
        ),
    ]
