# Generated by Django 5.0.7 on 2024-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='service_provider',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('CY', 'Company'), ('PE', 'Private Entrepreneur')], default='', max_length=100, null=True),
        ),
    ]
